export const ModuleName =  {
    CRM:'CRM',FINANCE :'FINANCE',MART:'MART'
}

export const INJECT_POSITION={
    INSERT_BEFORE_ELEMENT:'INSERT_BEFORE',
    INSERT_AFTER_ELEMENT:'INSERT_AFTER',
    INSERT_IN_ELEMENT:'INSER_IN'
}